[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "github-actions-optimizer"
version = "0.1.0-dev"
description = "Comprehensive GitHub Actions workflow optimization platform"
readme = "README.md"
license = {text = "GPL-3.0-or-later"}
authors = [
    {name = "Torsten Marco Knodt", email = "torsten.knodt+com.github.datas-world.github-actions-optimizer@datas-world.de"}
]
keywords = ["github-actions", "optimization", "cost-analysis", "workflow"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Quality Assurance",
    "Topic :: System :: Monitoring",
]
requires-python = ">=3.13"
dependencies = [
    "PyGithub>=2.1.1",
    "requests>=2.31.0",
    "pandas>=2.0.0",
    "numpy>=1.24.0",
    "pydantic>=2.0.0",
    "psutil>=5.9.0",
    "distro>=1.8.0",
    "tqdm>=4.65.0",
    "PyYAML>=6.0",
]

[project.optional-dependencies]
dev = [
    "black>=23.0.0",
    "isort>=5.12.0",
    "flake8>=6.0.0",
    "mypy>=1.5.0",
    "pytest>=7.4.0",
    "pre-commit>=3.4.0",
]

[project.urls]
Homepage = "https://github.com/datas-world/github-actions-optimizer"
Repository = "https://github.com/datas-world/github-actions-optimizer.git"
Issues = "https://github.com/datas-world/github-actions-optimizer/issues"

[project.scripts]
github-actions-optimizer = "github_actions_optimizer:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["github_actions_optimizer*"]

[tool.black]
line-length = 88
target-version = ['py313']

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.pytest.ini_options]
minversion = "7.0"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
