name: Pre-commit

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    # Auto-update pre-commit hooks weekly on Mondays at 4 AM UTC
    - cron: '0 4 * * 1'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  pre-commit:
    name: Pre-commit hooks
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install system dependencies
        uses: awalsh128/cache-apt-pkgs-action@2c09a5e66da6c8016428a2172bd76e5e4f14bb17 # v1.5.3
        with:
          packages: jq
          version: 1.0

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pip install -e .[dev]

      # FIXME: Caching temporarily disabled due to SHA pinning requirements
      # Issue #2: Re-enable caching in GitHub Actions workflows after SHA pinning resolution
      # See: https://github.com/datas-world/github-actions-optimizer/issues/2
      # The organization requires all actions to be pinned to commit SHAs, but actions/cache@v4
      # internally uses unpinned dependencies that cause workflow failures.
      # - name: Cache pre-commit hooks
      #   uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      #   with:
      #     path: ~/.cache/pre-commit
      #     key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
      #     restore-keys: |
      #       pre-commit-${{ runner.os }}-

      - name: Run pre-commit on all files
        run: |
          pre-commit install
          pre-commit run --all-files --show-diff-on-failure

  auto-update:
    name: Auto-update pre-commit hooks
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Update pre-commit hooks
        run: |
          pre-commit autoupdate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@18e469570b1cf0dfc11d60ec121099f8ff3e617a # v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'ci: update pre-commit hooks'
          title: 'chore: update pre-commit hooks'
          body: |
            ## Pre-commit Hook Updates

            This PR automatically updates pre-commit hooks to their latest versions.

            ### Changes
            - Updated pre-commit hook versions in `.pre-commit-config.yaml`

            ### Testing
            - [ ] All pre-commit hooks pass
            - [ ] CI pipeline completes successfully

            Auto-generated by GitHub Actions.
          branch: chore/update-pre-commit-hooks
          delete-branch: true
