name: Workflow Status Monitor

on:
  workflow_run:
    workflows: ["Main CI/CD Pipeline"]
    types:
      - completed
  schedule:
    # Check for stuck workflows every 30 minutes
    - cron: '*/30 * * * *'

permissions:
  actions: write
  contents: read
  checks: read

jobs:
  monitor-status:
    name: Monitor Workflow Status
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check workflow status and re-trigger if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Monitoring workflow status..."
          
          # Get the current branch or PR head ref
          if [ "${{ github.event_name }}" = "workflow_run" ]; then
            BRANCH="${{ github.event.workflow_run.head_branch }}"
            WORKFLOW_ID="${{ github.event.workflow_run.id }}"
            echo "Monitoring workflow run #${WORKFLOW_ID} on branch ${BRANCH}"
          else
            # For scheduled runs, check the main branch
            BRANCH="main"
            echo "Scheduled monitoring check for branch ${BRANCH}"
          fi
          
          # Get the latest workflow runs for the Main CI/CD Pipeline
          LATEST_RUNS=$(gh api \
            "/repos/${{ github.repository }}/actions/workflows/main.yml/runs?branch=${BRANCH}&per_page=5" \
            --jq '.workflow_runs[] | select(.status != "in_progress" and .status != "queued")')
          
          # Check if there are any recent failed runs that need attention
          FAILED_RUNS=$(echo "$LATEST_RUNS" | jq -r 'select(.conclusion == "failure") | .id' | head -1)
          
          if [ -n "$FAILED_RUNS" ]; then
            echo "Found failed workflow run: $FAILED_RUNS"
            
            # Check if there are any in-progress or queued runs
            IN_PROGRESS=$(gh api \
              "/repos/${{ github.repository }}/actions/workflows/main.yml/runs?branch=${BRANCH}&status=in_progress" \
              --jq '.workflow_runs | length')
            
            QUEUED=$(gh api \
              "/repos/${{ github.repository }}/actions/workflows/main.yml/runs?branch=${BRANCH}&status=queued" \
              --jq '.workflow_runs | length')
            
            echo "In progress runs: $IN_PROGRESS, Queued runs: $QUEUED"
            
            if [ "$IN_PROGRESS" -eq 0 ] && [ "$QUEUED" -eq 0 ]; then
              echo "No workflows currently running. Considering re-trigger..."
              
              # Get the failed run details
              FAILED_RUN_INFO=$(gh api "/repos/${{ github.repository }}/actions/runs/$FAILED_RUNS")
              RUN_AGE_MINUTES=$(echo "$FAILED_RUN_INFO" | jq -r '
                (now - (.created_at | strptime("%Y-%m-%dT%H:%M:%SZ") | mktime)) / 60 | floor
              ')
              
              echo "Failed run is $RUN_AGE_MINUTES minutes old"
              
              # Only re-trigger if the failure is recent (within last 2 hours) and not too frequent
              if [ "$RUN_AGE_MINUTES" -lt 120 ]; then
                echo "Re-triggering workflow for recent failure..."
                
                # Re-run the failed workflow
                gh api \
                  --method POST \
                  "/repos/${{ github.repository }}/actions/runs/$FAILED_RUNS/rerun" \
                  --silent
                
                echo "✅ Re-triggered failed workflow run #$FAILED_RUNS"
              else
                echo "Failed run is too old, not re-triggering automatically"
              fi
            else
              echo "Workflows are currently running, skipping re-trigger"
            fi
          else
            echo "No failed workflow runs found requiring attention"
          fi