name: Workflow Failure Tracker

on:
  workflow_run:
    workflows: ["CI", "CodeQL Analysis", "Pre-commit"]
    types:
      - completed

permissions:
  contents: read
  issues: write
  actions: read

jobs:
  track-failures:
    name: Track Workflow Failures
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get workflow run details
        id: workflow-details
        run: |
          echo "workflow_name=${{ github.event.workflow_run.name }}" >> $GITHUB_OUTPUT
          echo "workflow_run_id=${{ github.event.workflow_run.id }}" >> $GITHUB_OUTPUT
          echo "workflow_url=${{ github.event.workflow_run.html_url }}" >> $GITHUB_OUTPUT
          echo "workflow_head_sha=${{ github.event.workflow_run.head_sha }}" >> $GITHUB_OUTPUT
          echo "workflow_head_branch=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_OUTPUT
          echo "workflow_event=${{ github.event.workflow_run.event }}" >> $GITHUB_OUTPUT
          echo "workflow_created_at=${{ github.event.workflow_run.created_at }}" >> $GITHUB_OUTPUT

      - name: Check for existing issue
        id: check-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_NAME: ${{ steps.workflow-details.outputs.workflow_name }}
        run: |
          # Search for existing issues with the workflow failure label
          ISSUE_TITLE="Workflow Failure: ${WORKFLOW_NAME}"
          
          # Use GitHub CLI to search for existing issues
          EXISTING_ISSUE=$(gh issue list --label "workflow-failure" --state open --json number,title | jq -r ".[] | select(.title == \"${ISSUE_TITLE}\") | .number")
          
          if [ -n "$EXISTING_ISSUE" ]; then
            echo "issue_exists=true" >> $GITHUB_OUTPUT
            echo "issue_number=$EXISTING_ISSUE" >> $GITHUB_OUTPUT
            echo "Found existing issue #$EXISTING_ISSUE"
          else
            echo "issue_exists=false" >> $GITHUB_OUTPUT
            echo "No existing issue found"
          fi

      - name: Create new issue
        if: steps.check-issue.outputs.issue_exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_NAME: ${{ steps.workflow-details.outputs.workflow_name }}
          WORKFLOW_URL: ${{ steps.workflow-details.outputs.workflow_url }}
          WORKFLOW_RUN_ID: ${{ steps.workflow-details.outputs.workflow_run_id }}
          HEAD_SHA: ${{ steps.workflow-details.outputs.workflow_head_sha }}
          HEAD_BRANCH: ${{ steps.workflow-details.outputs.workflow_head_branch }}
          WORKFLOW_EVENT: ${{ steps.workflow-details.outputs.workflow_event }}
          CREATED_AT: ${{ steps.workflow-details.outputs.workflow_created_at }}
        run: |
          # Create issue body using heredoc to avoid YAML escaping issues
          cat > issue_body.md << EOF
          ## Workflow Failure Report

          This issue tracks failures in the **${WORKFLOW_NAME}** workflow that are not related to specific PR changes and require attention.

          ### Current Failure Details

          **Failed Run:** [Workflow Run #${WORKFLOW_RUN_ID}](${WORKFLOW_URL})
          - **Branch:** ${HEAD_BRANCH}
          - **Commit:** ${HEAD_SHA}
          - **Event:** ${WORKFLOW_EVENT}
          - **Timestamp:** ${CREATED_AT}

          ### Investigation Checklist

          - [ ] Review the failed workflow run logs
          - [ ] Identify if this is a recurring issue
          - [ ] Determine if this is related to infrastructure, dependencies, or code changes
          - [ ] Check if similar failures occurred in other repositories
          - [ ] Implement a fix or workaround

          ### Proposed Solution

          _To be updated as investigation progresses._

          ---

          **Note:** This issue was automatically created by the Workflow Failure Tracker.

          ### Failure History

          1. **${CREATED_AT}** - [Run #${WORKFLOW_RUN_ID}](${WORKFLOW_URL}) on branch \`${HEAD_BRANCH}\`
          EOF

          # Create the issue using GitHub CLI
          ISSUE_NUMBER=$(gh issue create \
            --title "Workflow Failure: ${WORKFLOW_NAME}" \
            --body-file issue_body.md \
            --label "workflow-failure,automated,bug" | grep -oE '[0-9]+$')
          
          echo "Created new issue #$ISSUE_NUMBER"

      - name: Update existing issue
        if: steps.check-issue.outputs.issue_exists == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ steps.check-issue.outputs.issue_number }}
          WORKFLOW_NAME: ${{ steps.workflow-details.outputs.workflow_name }}
          WORKFLOW_URL: ${{ steps.workflow-details.outputs.workflow_url }}
          WORKFLOW_RUN_ID: ${{ steps.workflow-details.outputs.workflow_run_id }}
          HEAD_SHA: ${{ steps.workflow-details.outputs.workflow_head_sha }}
          HEAD_BRANCH: ${{ steps.workflow-details.outputs.workflow_head_branch }}
          CREATED_AT: ${{ steps.workflow-details.outputs.workflow_created_at }}
        run: |
          # Create comment body using heredoc
          cat > comment_body.md << EOF
          ## New Failure Occurrence

          The **${WORKFLOW_NAME}** workflow failed again.

          **Details:**
          - **Run:** [#${WORKFLOW_RUN_ID}](${WORKFLOW_URL})
          - **Branch:** ${HEAD_BRANCH}
          - **Commit:** ${HEAD_SHA}
          - **Timestamp:** ${CREATED_AT}

          Please review if this failure pattern indicates a recurring issue that needs investigation.
          EOF

          # Add comment to existing issue
          gh issue comment ${ISSUE_NUMBER} --body-file comment_body.md
          
          echo "Updated existing issue #${ISSUE_NUMBER} with new failure occurrence"